"""Added password field

Revision ID: 020b8de65a95
Revises: f9b648f0f308
Create Date: 2018-01-23 15:50:38.223903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020b8de65a95'
down_revision = 'f9b648f0f308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=120), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
